### ISSUE TITLE
Failing Travis build

### ISSUE THREAD

**Issue by hidingmode** [CS2103-AY1819S1-T13-3/main#53]
Need to figure out why Travis build is failing.
Looking at the travis logs, it seems like the allTests script (which I assume is running all test files) is failing. I ran `gradlew allTests` in my local repo and it ends successfully. So I'm not sure why.

**Comment by handshou** [comment]
Some exceptions found.

Within logging message shown below, see https://stackoverflow.com/questions/14025718/javafx-toolkit-not-initialized-when-trying-to-play-an-mp3-file-through-mediap/38883432.
Outside of this log, see https://www.geeksforgeeks.org/classnotfoundexception-vs-noclassdeffounderror-java/.

On running model tests, while tests are passing, I get these exceptions.
**Note**: I'm currently running on jdk-10.0.2.

```
/Library/Java/JavaVirtualMachines/jdk-10.0.2.jdk/Contents/Home/bin/java -ea -Didea.test.cyclic.buffer.size=1048576 "-javaagent:/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar=51684:/Applications/IntelliJ IDEA.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath "/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar:/Applications/IntelliJ IDEA.app/Contents/plugins/junit/lib/junit-rt.jar:/Applications/IntelliJ IDEA.app/Contents/plugins/junit/lib/junit5-rt.jar:/Users/hans/.m2/repository/org/junit/platform/junit-platform-launcher/1.1.0/junit-platform-launcher-1.1.0.jar:/Users/hans/.m2/repository/org/apiguardian/apiguardian-api/1.0.0/apiguardian-api-1.0.0.jar:/Users/hans/.m2/repository/org/junit/platform/junit-platform-engine/1.1.0/junit-platform-engine-1.1.0.jar:/Users/hans/.m2/repository/org/junit/platform/junit-platform-commons/1.1.0/junit-platform-commons-1.1.0.jar:/Users/hans/.m2/repository/org/opentest4j/opentest4j/1.0.0/opentest4j-1.0.0.jar:/Users/hans/code/nus/cs2103/main/out/test/classes:/Users/hans/code/nus/cs2103/main/out/test/resources:/Users/hans/code/nus/cs2103/main/out/production/classes:/Users/hans/code/nus/cs2103/main/out/production/resources:/Users/hans/.gradle/caches/modules-2/files-2.1/com.google.code.gson/gson/2.8.5/f645ed69d595b24d4cf8b3fbb64cc505bede8829/gson-2.8.5.jar:/Users/hans/.gradle/caches/modules-2/files-2.1/org.controlsfx/controlsfx/8.40.11/61694ec2668cc69116e970c7513aa3501179bc00/controlsfx-8.40.11.jar:/Users/hans/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.datatype/jackson-datatype-jsr310/2.7.4/390dbf17d4eb29a6157c6b9dcd9c93e7acac714/jackson-datatype-jsr310-2.7.4.jar:/Users/hans/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-databind/2.7.4/1e9c6f3659644aeac84872c3b62d8e363bf4c96d/jackson-databind-2.7.4.jar:/Users/hans/.gradle/caches/modules-2/files-2.1/com.google.guava/guava/19.0/6ce200f6b23222af3d8abb6b6459e6c44f4bb0e9/guava-19.0.jar:/Users/hans/.gradle/caches/modules-2/files-2.1/javax.xml.bind/jaxb-api/2.2.8/f0287831b3e3550b82b5bd19152d460061859ce6/jaxb-api-2.2.8.jar:/Users/hans/.gradle/caches/modules-2/files-2.1/com.sun.xml.bind/jaxb-impl/2.3.0/3a3c6a62719d967175b76b63925f1fb495f11437/jaxb-impl-2.3.0.jar:/Users/hans/.gradle/caches/modules-2/files-2.1/com.sun.xml.bind/jaxb-core/2.3.0/d044c784e41d026778693fb44a8026c1fd9a7506/jaxb-core-2.3.0.jar:/Users/hans/.gradle/caches/modules-2/files-2.1/javax.activation/activation/1.1.1/485de3a253e23f645037828c07f1d7f1af40763a/activation-1.1.1.jar:/Users/hans/.gradle/caches/modules-2/files-2.1/org.testfx/testfx-junit/4.0.12-alpha/bdf68aa6ab3f7c2ed468c3ef25451b6ed414b143/testfx-junit-4.0.12-alpha.jar:/Users/hans/.gradle/caches/modules-2/files-2.1/junit/junit/4.12/2973d150c0dc1fefe998f834810d68f278ea58ec/junit-4.12.jar:/Users/hans/.gradle/caches/modules-2/files-2.1/org.testfx/testfx-core/4.0.12-alpha/55d68835a7f5c0f3b5630a2a542e0880f2548e7f/testfx-core-4.0.12-alpha.jar:/Users/hans/.gradle/caches/modules-2/files-2.1/org.junit.vintage/junit-vintage-engine/5.1.0/a752dd045d08753ac77622dc83b584dc5abda1e1/junit-vintage-engine-5.1.0.jar:/Users/hans/.gradle/caches/modules-2/files-2.1/org.junit.jupiter/junit-jupiter-api/5.1.0/370218fbc7ce9cf0600c4b5db400bccdf0c01a48/junit-jupiter-api-5.1.0.jar:/Users/hans/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-annotations/2.7.0/19f42c154ffc689f40a77613bc32caeb17d744e3/jackson-annotations-2.7.0.jar:/Users/hans/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-core/2.7.4/b8f38a249116b66d804a5ca2b14a3459b7913a94/jackson-core-2.7.4.jar:/Users/hans/.gradle/caches/modules-2/files-2.1/org.junit.jupiter/junit-jupiter-engine/5.1.0/c54b96b465bb5b49c7708d734a4180dd95422754/junit-jupiter-engine-5.1.0.jar:/Users/hans/.gradle/caches/modules-2/files-2.1/org.hamcrest/hamcrest-core/1.3/42a25dc3219429f0e5d060061f71acb49bf010a0/hamcrest-core-1.3.jar:/Users/hans/.gradle/caches/modules-2/files-2.1/org.assertj/assertj-core/3.9.1/c5ce126b15f28d56cd8f960c1a6a058b9c9aea87/assertj-core-3.9.1.jar:/Users/hans/.gradle/caches/modules-2/files-2.1/org.junit.platform/junit-platform-commons/1.1.0/d6aa21029f9cedfb4cc8a9e9efc0bd97987205b8/junit-platform-commons-1.1.0.jar:/Users/hans/.gradle/caches/modules-2/files-2.1/org.testfx/testfx-internal-java9/4.0.12-alpha/231cf5c0ec5bf20c3fe7003283c83826e006b5ae/testfx-internal-java9-4.0.12-alpha.jar:/Users/hans/.gradle/caches/modules-2/files-2.1/org.testfx/openjfx-monocle/jdk-9+181/c412deb11898e532c46e4d6c2808e4227f120445/openjfx-monocle-jdk-9+181.jar:/Users/hans/.gradle/caches/modules-2/files-2.1/org.apiguardian/apiguardian-api/1.0.0/3ef5276905e36f4d8055fe3cb0bdcc7503ffc85d/apiguardian-api-1.0.0.jar:/Users/hans/.gradle/caches/modules-2/files-2.1/org.opentest4j/opentest4j/1.0.0/6f09c598e9ff64bf0ce2fa7e7de49a99ba83c0b4/opentest4j-1.0.0.jar:/Users/hans/.gradle/caches/modules-2/files-2.1/org.testfx/testfx-internal-java8/4.0.12-alpha/2bef7549a8e84298a8cc47f6dc7e37675a9dcebc/testfx-internal-java8-4.0.12-alpha.jar:/Users/hans/.gradle/caches/modules-2/files-2.1/org.junit.platform/junit-platform-engine/1.1.0/2596bd4d909e7ea8d029272db4338075445d731b/junit-platform-engine-1.1.0.jar" com.intellij.rt.execution.junit.JUnitStarter -ideVersion5 -junit5 @w@/private/var/folders/f0/7km_2l9x4b3dmn1q2khbx_vr0000gn/T/idea_working_dirs_junit.tmp @/private/var/folders/f0/7km_2l9x4b3dmn1q2khbx_vr0000gn/T/idea_junit.tmp -socket51683
Exception in thread "Thread-6" Exception in thread "Thread-8" java.lang.IllegalStateException: Toolkit not initialized
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.runLater(PlatformImpl.java:396)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.runLater(PlatformImpl.java:391)
	at javafx.graphics/javafx.application.Platform.runLater(Platform.java:150)
	at javafx.media/javafx.scene.media.Media$_MetadataListener.onMetadata(Media.java:543)
	at javafx.media/com.sun.media.jfxmediaimpl.MetadataParserImpl.done(MetadataParserImpl.java:113)
	at javafx.media/com.sun.media.jfxmediaimpl.platform.java.ID3MetadataParser.parse(ID3MetadataParser.java:237)
	at javafx.media/com.sun.media.jfxmediaimpl.MetadataParserImpl.run(MetadataParserImpl.java:96)
java.lang.IllegalStateException: Toolkit not initialized
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.runLater(PlatformImpl.java:396)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.runLater(PlatformImpl.java:391)
	at javafx.graphics/javafx.application.Platform.runLater(Platform.java:150)
	at javafx.media/javafx.scene.media.Media$_MetadataListener.onMetadata(Media.java:543)
	at javafx.media/com.sun.media.jfxmediaimpl.MetadataParserImpl.done(MetadataParserImpl.java:113)
	at javafx.media/com.sun.media.jfxmediaimpl.platform.java.ID3MetadataParser.parse(ID3MetadataParser.java:237)
	at javafx.media/com.sun.media.jfxmediaimpl.MetadataParserImpl.run(MetadataParserImpl.java:96)
Oct 19, 2018 7:13:10 PM seedu.jxmusic.commons.core.EventsCenter post
INFO: ------[Event Posted] seedu.jxmusic.commons.events.model.LibraryChangedEvent: number of playlists 1
Exception in thread "Thread-13" java.lang.IllegalStateException: Toolkit not initialized
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.runLater(PlatformImpl.java:396)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.runLater(PlatformImpl.java:391)
	at javafx.graphics/javafx.application.Platform.runLater(Platform.java:150)
	at javafx.media/javafx.scene.media.Media$_MetadataListener.onMetadata(Media.java:543)
	at javafx.media/com.sun.media.jfxmediaimpl.MetadataParserImpl.done(MetadataParserImpl.java:113)
	at javafx.media/com.sun.media.jfxmediaimpl.platform.java.ID3MetadataParser.parse(ID3MetadataParser.java:237)
	at javafx.media/com.sun.media.jfxmediaimpl.MetadataParserImpl.run(MetadataParserImpl.java:96)
Exception in thread "Thread-14" java.lang.IllegalStateException: Toolkit not initialized
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.runLater(PlatformImpl.java:396)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.runLater(PlatformImpl.java:391)
	at javafx.graphics/javafx.application.Platform.runLater(Platform.java:150)
	at javafx.media/javafx.scene.media.Media$_MetadataListener.onMetadata(Media.java:543)
	at javafx.media/com.sun.media.jfxmediaimpl.MetadataParserImpl.done(MetadataParserImpl.java:113)
	at javafx.media/com.sun.media.jfxmediaimpl.platform.java.ID3MetadataParser.parse(ID3MetadataParser.java:237)
	at javafx.media/com.sun.media.jfxmediaimpl.MetadataParserImpl.run(MetadataParserImpl.java:96)

Process finished with exit code 0

```
